 
plantDiseaseClasses = [
    ['Apple', 'Apple Scab'],
    ['Apple', 'Black Rot'],
    ['Apple', 'Cedar Apple Rust'],
    ['Apple', 'Healthy'],
    ['Blueberry', 'Healthy'],
    ['Cherry(including sour)', 'Powdery Mildew'],
    ['Cherry(including sour)', 'Healthy'],
    ['Corn(Maize)', 'Cercospora Leaf Spot Gray Leaf Spot'],
    ['Corn(Maize)', 'Common Rust '],
    ['Corn(Maize)', 'Northern Leaf Blight'],
    ['Corn(Maize)', 'Healthy'],
    ['Grape', 'Black rot'],
    ['Grape', 'Esca(Black Measles)'],
    ['Grape', 'Leaf Blight(Isariopsis Leaf Spot)'],
    ['Grape', 'Healthy'],
    ['Orange', 'Haunglongbing(Citrus Greening)'],
    ['Peach', 'Bacterial Spot'],
    ['Peach', 'Healthy'],
    ['Pepper Bell', 'Bacterial Spot'],
    ['Pepper Bell', 'Healthy'],
    ['Potato', 'Early Blight'],
    ['Potato', 'Late Blight'],
    ['Potato', 'Healthy'],
    ['Raspberry', 'Healthy'],
    ['Soybean', 'Healthy'],
    ['Squash', 'Powdery Mildew'],
    ['Strawberry', 'Leaf Scorch'],
    ['Strawberry', 'Healthy'],
    ['Tomato', 'Bacterial Spot'],
    ['Tomato', 'Early Blight'],
    ['Tomato', 'Late Blight'],
    ['Tomato', 'Leaf Mold'],
    ['Tomato', 'Septoria leaf Spot'],
    ['Tomato', 'Spider Mites Two-spotted Spider Bite'],
    ['Tomato', 'Target Spot'],
    ['Tomato', 'Tomato Yellow Leaf Curl Virus'],
    ['Tomato', 'Tomato Mosaic Virus'],
    ['Tomato', 'Healthy'],    
]
